import "./kit.css";

export { TablaRegistros, ChipFiltro } from "./tabla";
export type { Columna, Filtro, Tono } from "./tabla";
export { TarjetaInsight, Chispa } from "./insight";
export type { Insight } from "./insight";
export { TarjetaAprobacion } from "./aprobacion";
export { ChipHerramienta, ChipsHerramienta } from "./chips-herramienta";
export type { EstadoHerramienta } from "./chips-herramienta";
export { FilaTarea, FilasTarea } from "./filas-tarea";
export type { EstadoTarea } from "./filas-tarea";
export { PaletaComandos, useAtajoPaleta } from "./paleta";
export type { Comando, GrupoComandos } from "./paleta";
export { Dialogo } from "./dialogo";
export { Pestanas, PanelPestana } from "./pestanas";
export type { Pestana } from "./pestanas";
export { ProveedorAvisos, useAvisos } from "./avisos";
export type { Aviso, TonoAviso } from "./avisos";
export { CifraAnimada } from "./cifra";
export { EsqueletoLinea, EsqueletoTabla, EsqueletoCifra, EsqueletoTarjeta } from "./esqueleto";
export { MarcaExito } from "./marca-exito";
export { TextoFluye, Pensando } from "./flujo";
export type { PasoPensando } from "./flujo";
export { GraficaLineas, BarrasMini, BarraSegmentada, Avance, Kpi, FilaKpis, ListaConceptos } from "./graficas";
export type { Serie, Formato } from "./graficas";
