# Secrets Manager de la cuenta como almacén de External Secrets (Pod Identity; solo noprod/ y el de RDS).
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: mx-central-1
